// src/components/Navbar.jsx
import react from '../assets/react.png'
import { useState } from "react";
import { Link } from "react-scroll"
import { GrLanguage } from "react-icons/gr";
import { FaBars, FaXmark } from 'react-icons/fa6';
const Navbar = () => {
    const [isMenuOpen, setIsOpenMenu] = useState(false);

    const toggleMenu = () => { setIsOpenMenu(!isMenuOpen) }

    const navItems = [
        { link: "Overview", path: "home" },
        { link: "Feature", path: "feature" },
        { link: "About", path: "about" },
        { link: "Pricing", path: "pricing" },


    ]
    return (
        <>
            <nav className='bg-white border-b md:px-14 p-4 max-w-screen-2xl mx-auto text-primary fixed top-0 left-0 right-0'>
                <div className='text-lg container mx-auto flex justify-between items-center font-medium'>
                    <div className='flex space-x-14 items-center'>
                        <a href="/" className="text-2xl font-semibold flex items-center space-x-3 text-primary">
                            <img src={react} className="w-10 inline-block items-center" /> <span>XYZ</span></a>
                        <ul className='md:flex space-x-12 hidden'>
                            {
                                navItems.map(({ link, path }) => <Link key={link} activeClass='active' spy={true} smooth={true} offset={-100} to={path}
                                    className='block hover:text-gray-300 cursor-pointer'>{link}</Link>)
                            }
                        </ul>
                    </div>

                    <div className='space-x-12 hidden md:flex items-center'>
                        <a href="/" className='hidden lg:flex items-center hover:text-secondary'>
                            <GrLanguage className='mr-2' /><span>Language</span></a>
                        <button className='bg-secondary py-2 px-4 transition-all duration-300 rounded 
                hover:text-white hover:bg-indigo-600'>Sign up</button>
                    </div>

                    <div className='md:hidden'>
                        <button onClick={toggleMenu}
                            className='text-white focus:outline-none focus:text-gray-300'>
                            {
                                isMenuOpen ? (<FaXmark className='w-6 h-6 text-primary' />) :
                                    (<FaBars className='w-6 h-6 text-primary' />)
                            }
                        </button>
                    </div>
                </div>
            </nav>
            <div className={`space-y-4 px-4 pt-24 pb-5 text-xl bg-secondary 
            ${isMenuOpen? "block fixed top-0 right-0 left-0" : "hidden"} `}>
                {
                    navItems.map(({ link, path }) => <Link key={link} activeClass='active' spy={true} smooth={true} offset={-80} to={path}
                        className='block text-white hover:text-gray-300' onClick={toggleMenu}>{link}</Link>)
                }
            </div>
        </>
    );
};

export default Navbar;

// src/app/components/navbar/navbar.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  Logo = '../../../assets/react.png'
  global = '../../../assets/global.png'
  Menu = false;
  AbrirMenu = '../../../assets/menuOpen.png'
  CerrarMenu = '../../../assets/menuAbierto2.png'
  navItems = [
    { link: "Overview", path: "home" },
    { link: "Feature", path: "feature" },
    { link: "About", path: "about" },
    { link: "Pricing", path: "pricing" },
  ]

  MenuAbierto(){
    this.Menu = !this.Menu;
  }


}

<nav class='bg-white border-b md:px-14 p-4 max-w-screen-2xl mx-auto text-primary fixed top-0 left-0 right-0'>
  <div class='text-lg container mx-auto flex justify-between items-center font-medium'>
      <div class='flex space-x-14 items-center'>
          <a href="/" class="text-2xl font-semibold flex items-center space-x-3 text-primary">
              <img src={{Logo}} class="w-10 inline-block items-center" /> <span>XYZ</span></a>
          <ul class='md:flex space-x-12 hidden' *ngFor="let item of navItems">
            <li class="block hover:text-gray-300 cursor-pointer">{{item.link}}</li>
          </ul>
      </div>

      <div class='space-x-12 hidden md:flex items-center'>
          <a href="/" class='hidden lg:flex items-center hover:text-secondary'>
              <img src={{global}} class="mr-2 w-10 inline-block items-center"><span>Language</span></a>
          <button class='bg-secondary py-2 px-4 transition-all duration-300 rounded
  hover:text-white hover:bg-indigo-600'>Sign up</button>
      </div>

      <div class='md:hidden'>
          <button (click)="MenuAbierto()"
              class='text-white focus:outline-none focus:text-gray-300'>
              <a *ngIf="Menu" class='w-6 h-6 text-primary'><img class='w-6 h-6 text-primary' src={{CerrarMenu}}></a>
              <a *ngIf="!Menu" class='w-6 h-6 text-primary'><img class='w-6 h-6 text-primary' src={{AbrirMenu}}></a>
          </button>
      </div>
  </div>
</nav>
<div *ngIf="Menu" class="space-y-4 px-4 pt-2 pb-5 text-xl bg-secondary block fixed mt-20 top-0 right-0 left-0">
          <ul class='sm:flex space-x-12 hidden' *ngFor="let item of navItems">
            <a class="class='block text-white hover:text-gray-300'">{{item.link}}</a>
          </ul>
</div>
