// src/components/Home.jsx
import Banner from '../shared/Banner'

import bannerbg from '../assets/bannerbg.png'
const Home = () => {
    return (
        <div className="md:px-12 p-4 max-w-screen-2xl mx-auto mt-24" id='home'>
               <Banner banner={bannerbg} heading={"Develop your skills without diligence"} 
               subheading={"A good example of a paragraph contains a topic sentence, details and a conclusion. There are many different kinds of animals that live in China."}
               btn1={"Get Started"} btn2={"Discount"}
               />
        </div>
    );
};

export default Home;

// src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { BannerComponent } from '../../shared/banner/banner.component';
import { CommonModule } from '@angular/common';
@Component({
  selector: 'app-home',
  standalone: true,
  imports: [BannerComponent, CommonModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {
  public banner = '../../../assets/bannerbg.png'




}

<div class="md:px-12 p-4 max-w-screen-2xl mx-auto mt-24" id='home'>
  <!-- <Banner banner={bannerbg} heading={"Develop your skills without diligence"}
  subheading={"A good example of a paragraph contains a topic sentence, details and a conclusion. There are many different kinds of animals that live in China."}
  btn1={"Get Started"} btn2={"Discount"}
  /> -->
  <app-banner [bannerbg]="banner" [heading]="'Develop your skills without diligence'"
  [subheading]="'A good example of a paragraph contains a topic sentence, details and a conclusion. There are many different kinds of animals that live in China.'"
  [btn1]="'Get Started'" [btn2]="'Discount'"></app-banner>
</div>
