// src/shared/Banner.jsx
import React from 'react';
import {motion} from 'framer-motion'
import {fadeIn} from '../variants'


const Banner = ({banner, heading, subheading, btn1, btn2}) => {
    return (
        <div className='gradientBg rounded-xl rounded-br-[80px] md:p-9 px-4 py-9'>
        <div className='flex flex-col md:flex-row-reverse 
        justify-between items-center gap-10'>
        <motion.div
        variants={fadeIn("down",0.2)}
        initial="hidden"
        whileInView={"show"}
        viewport={{once:false, amount: 0.7 }}
        >
                <img src={banner} alt="" className='lg:h-[386px] '/>
            </motion.div>
            <motion.div 
            variants={fadeIn("up",0.2)}
            initial="hidden"
            whileInView={"show"}
            viewport={{once:false, amount: 0.7 }}
            className="md:w-3/5 ">
                <h2 className='md:text-7xl text-4xl font-bold 
                text-white mb-6 leading-relaxed'>{heading}</h2>
                <p className='text-[#EBEBEB] text-2xl mb-8 '>{subheading}</p>
                <div className='space-x-5 space-y-4'>
                    <button className='btnPrimary'>{btn1}</button>
                    <button className='btnPrimary'>{btn2}</button>
                </div>
            </motion.div>
            
        </div>
    </div>
    );
};

export default Banner;

// src/app/shared/banner/banner.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-banner',
  standalone: true,
  imports: [],
  templateUrl: './banner.component.html',
  styleUrl: './banner.component.css'
})
export class BannerComponent {
  @Input() bannerbg?:string;
  @Input() heading?:string;
  @Input() subheading?:string;
  @Input() btn1?:string;
  @Input() btn2?:string;
}

<div Class='gradientBg rounded-xl rounded-br-[80px] md:p-9 px-4 py-9'>
  <div Class='flex flex-col md:flex-row-reverse
  justify-between items-center gap-10'>
  <div>
          <img src={{bannerbg}} alt="" Class='lg:h-[386px] '/>
      </div>
      <div
      Class="md:w-3/5 ">
          <h2 Class='md:text-7xl text-4xl font-bold
          text-white mb-6 leading-relaxed'>{{heading}}</h2>
          <p Class='text-[#EBEBEB] text-2xl mb-8 '>{{subheading}}</p>
          <div Class='space-x-5 space-y-4'>
              <button Class='btnPrimary'>{{btn1}}</button>
              <button Class='btnPrimary'>{{btn2}}</button>
          </div>
      </div>

  </div>
</div>
