// src/components/Pricing.jsx
import { useState } from "react";
import {motion} from 'framer-motion'
import {fadeIn} from '../variants'

const Pricing = () => {
    const [isYearly, setIsYearly] = useState(false);
    const packages = [
        {name:'Start', monthlyPrice: 19, yearlyPrice:199, description:'A common form of Lorem ipsum reads: Lore ipsum dolor sit amet, consectetur adipiscing elit.', green: 'src/assets/circverd.png'},
        {name:'Advance', monthlyPrice: 39, yearlyPrice:399, description:'A common form of Lorem ipsum reads: Lore ipsum dolor sit amet, consectetur adipiscing elit.', green: 'src/assets/circverd.png'},
        {name:'Premium', monthlyPrice: 59, yearlyPrice:599, description:'A common form of Lorem ipsum reads: Lore ipsum dolor sit amet, consectetur adipiscing elit.', green: 'src/assets/circverd.png'},
    ]
    return (
        <div className="md:px-14 p-4 max-w-s mx-auto py-10" id="pricing">
            <div className="text-center">
                <h2 className="md:text-5xl text-3xl font-extrabold text-primary mb-2">Here are all our plans</h2>
                <p className="text-tartiary md:w-1/3 mx-auto px-4 ">A simple paragraph is comprised of three major components. The wichis often a declarative sentence.</p>

                <div className="mt-16">
                    <label htmlFor="toggle" className="inline-flex items-center cursor-pointer">
                        <span className="mr-8 text-2xl font-semibold">Monthly</span>
                        <div className="w-14 h-6 bg-gray-300 rounded-full transition duration-200 ease-in-out">
                            <div className={`w-6 h-6 rounded-full ${isYearly ? "bg-primary ml-8" : "bg-gray-500"}`}></div>
                        </div>
                        <span className="ml-8 text-2xl font-semibold">Yearly</span>
                    </label>
                    <input type="checkbox" id="toggle" className="hidden" checked={isYearly} onChange={()=>{setIsYearly(!isYearly)}} />
                </div>

            </div>

            <motion.div 
            variants={fadeIn("up",0.2)}
            initial="hidden"
            whileInView={"show"} 
            viewport={{once:false, amount:0.5}}
            className="grid sm:grid-cols-2 lg:grid-cols-3 gap-10 mt-20 md:w-11/12 mx-auto">
                {
                    packages.map((pkg,index)=><div key={index} className="border py-10 md:px-6 px-4 rounded-lg shadow-3xl">
                        <h3 className="text-3xl font-bold text-center text-primary">{pkg.name}</h3>
                        <p className="text-tartiary text-center my-5">{pkg.description}</p>
                        <p className="mt-5 text-center text-secondary text-4xl font-bold">
                            {isYearly? `$${pkg.yearlyPrice}`:`$${pkg.monthlyPrice}`} 
                            <span className="text-base text-tartiary font-medium">/{isYearly? 'year': 'month'}</span>
                        </p>
                        <ul className="mt-4 space-y-2 px-4">
                            <li className="flex gap-3 items-center"><img src={pkg.green} alt="" className="w-4 h-4 "/>Videos of Lesson</li>
                            <li className="flex gap-3 items-center"><img src={pkg.green} alt="" className="w-4 h-4 "/>Homework check</li>
                            <li className="flex gap-3 items-center"><img src={pkg.green} alt="" className="w-4 h-4 "/>Additional practical task</li>
                            <li className="flex gap-3 items-center"><img src={pkg.green} alt="" className="w-4 h-4 "/>Monthly conferences</li>
                            <li className="flex gap-3 items-center"><img src={pkg.green} alt="" className="w-4 h-4 "/>Personal advice from teachers</li>
                        </ul>
                        <div className="w-full mx-auto mt-8 flex items-center justify-center">
                        <button className="btnPrimary">Get Started</button>
                        </div>
                    </div>)
                }
            </motion.div>

        </div>
    );
};

export default Pricing;

// src/app/components/pricing/pricing.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-pricing',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './pricing.component.html',
  styleUrl: './pricing.component.css'
})
export class PricingComponent {
  isYearly=false;

  packages = [
    {name:'Start', monthlyPrice: 19, yearlyPrice:199, description:'A common form of Lorem ipsum reads: Lore ipsum dolor sit amet, consectetur adipiscing elit.', green: '../../../assets/circverd.png'},
    {name:'Advance', monthlyPrice: 39, yearlyPrice:399, description:'A common form of Lorem ipsum reads: Lore ipsum dolor sit amet, consectetur adipiscing elit.', green: '../../../assets/circverd.png'},
    {name:'Premium', monthlyPrice: 59, yearlyPrice:599, description:'A common form of Lorem ipsum reads: Lore ipsum dolor sit amet, consectetur adipiscing elit.', green: '../../../assets/circverd.png'},
  ]
  setYearly(){
    this.isYearly = !this.isYearly;
  }
}

<div Class="md:px-14 p-4 max-w-s mx-auto py-10" id="pricing">
  <div Class="text-center">
    <h2 Class="md:text-5xl text-3xl font-extrabold text-primary mb-2">Here are all our plans</h2>
    <p Class="text-tartiary md:w-1/3 mx-auto px-4 ">A simple paragraph is comprised of three major components. The
      wichis often a declarative sentence.</p>

    <div Class="mt-16">
      <label htmlFor="toggle" Class="inline-flex items-center cursor-pointer">
        <span Class="mr-8 text-2xl font-semibold">Monthly</span>
        <div Class="w-14 h-6 bg-gray-300 rounded-full transition duration-200 ease-in-out">
          <div *ngIf="isYearly" Class="w-6 h-6 rounded-full bg-primary ml-8"></div>
          <div *ngIf="!isYearly" Class="w-6 h-6 rounded-full bg-gray-500"></div>
          <input type="checkbox" id="toggle" class="hidden" (change)="setYearly()" />
        </div>
        <span Class="ml-8 text-2xl font-semibold">Yearly</span>
      </label>

    </div>

  </div>

  <div Class="grid sm:grid-cols-2 lg:grid-cols-3 gap-10 mt-20 md:w-11/12 mx-auto">
    <div *ngFor="let item of packages" class="border py-10 md:px-6 px-4 rounded-lg shadow-3xl">
      <h3 Class="text-3xl font-bold text-center text-primary">{{item.name}}</h3>
      <p Class="text-tartiary text-center my-5">{{item.description}}</p>
      <p Class="mt-5 text-center text-secondary text-4xl font-bold" *ngIf="isYearly">
        ${{item.yearlyPrice}}
        <span Class="text-base text-tartiary font-medium">/year</span>
      </p>
      <p Class="mt-5 text-center text-secondary text-4xl font-bold" *ngIf="!isYearly">
        ${{item.monthlyPrice}}
        <span Class="text-base text-tartiary font-medium">/month</span>
      </p>
      <ul Class="mt-4 space-y-2 px-4">
        <li Class="flex gap-3 items-center"><img src={{item.green}} Class="w-3 h-4 " />Videos of Lesson</li>
        <li Class="flex gap-3 items-center"><img src={{item.green}} Class="w-4 h-4 " />Homework check</li>
        <li Class="flex gap-3 items-center"><img src={{item.green}} Class="w-4 h-4 " />Additional practical task</li>
        <li Class="flex gap-3 items-center"><img src={{item.green}} Class="w-4 h-4 " />Monthly conferences</li>
        <li Class="flex gap-3 items-center"><img src={{item.green}} Class="w-4 h-4 " />Personal advice from
          teachers</li>
      </ul>
      <div Class="w-full mx-auto mt-8 flex items-center justify-center">
        <button Class="btnPrimary">Get Started</button>
      </div>


    </div>
  </div>

</div>
