// src/app/components/about/about.component.ts
import { Component } from '@angular/core';
import {motion} from 'framer-motion'
@Component({
  selector: 'app-about',
  standalone: true,
  imports: [],
  templateUrl: './about.component.html',
  styleUrl: './about.component.css'
})
export class AboutComponent {
  aboutImage1 = '../../../assets/about1.png'
  bannerbg = '../../../assets/bannerbg.png'

}

<div Class="md:px-14 p-4 max-w-s mx-auto space-y-10" id='about'>
  <div Class='flex flex-col md:flex-row justify-between items-center gap-8'>

    <div Class='md:w-1/2'>
          <img src={{aboutImage1}} alt="" />
      </div>

      <div Class='md:w-2/5'>
          <h2 Class='md:text-5xl text-3xl font-bold text-primary mb-5 leading-normal'>We have been improving our product <span Class='text-secondary'>for many years.</span></h2>
          <p Class='text-tartiary text-lg mb-7'>A good example of a paragraph contains a topic conclusion. There are many different
              kinds of animals that live in China.</p>
          <button Class='btnPrimary'>Get Started</button>
      </div>

  </div>


  <div Class='flex flex-col md:flex-row-reverse justify-between items-center gap-8'>
      <div Class='md:w-1/2'>
          <img src={{bannerbg}} alt="" />
      </div>

      <div Class='md:w-2/5'>
          <h2 Class='md:text-5xl text-3xl font-bold text-primary mb-5 leading-normal'>You can practice any <span Class='text-secondary'>time convinent for you.</span></h2>
          <p Class='text-tartiary text-lg mb-7'>A good example of a paragraph contains a topic conclusion. There are many different
              kinds of animals that live in China.</p>
          <button Class='btnPrimary'>Get Started</button>
      </div>

  </div>
</div>

// src/components/About.jsx
import aboutImage1 from '../assets/about1.png'
import bannerbg from '../assets/bannerbg.png'
import {motion} from 'framer-motion'
import {fadeIn} from '../variants'

const About = () => {
    return (
        <div className="md:px-14 p-4 max-w-s mx-auto space-y-10" id='about'>
            <div
            
            className='flex flex-col md:flex-row justify-between items-center gap-8'>
                <motion.div
                variants={fadeIn("right",0.2)}
                initial="hidden"
                whileInView={"show"} 
                viewport={{once:false, amount:0.7}}
                className='md:w-1/2'>
                    <img src={aboutImage1} alt="" />
                </motion.div>

                <motion.div
                variants={fadeIn("left",0.3)}
                initial="hidden"
                whileInView={"show"}
                viewport={{once:false, amount:0.7}}
                className='md:w-2/5'>
                    <h2 className='md:text-5xl text-3xl font-bold text-primary mb-5 leading-normal'>We have been improving our product <span className='text-secondary'>for many years.</span></h2>
                    <p className='text-tartiary text-lg mb-7'>A good example of a paragraph contains a topic conclusion. There are many different 
                        kinds of animals that live in China.</p>
                    <button className='btnPrimary'>Get Started</button>
                </motion.div>

            </div>


            <div className='flex flex-col md:flex-row-reverse justify-between items-center gap-8'>
                <motion.div
                variants={fadeIn("up",0.2)}
                initial="hidden"
                whileInView={"show"}
                viewport={{once:false, amount:0.7}}
                className='md:w-1/2'>
                    <img src={bannerbg} alt="" />
                </motion.div>

                <motion.div 
                variants={fadeIn("right",0.2)}
                initial="hidden"
                whileInView={"show"}
                viewport={{once:false, amount:0.7}}
                className='md:w-2/5'>
                    <h2 className='md:text-5xl text-3xl font-bold text-primary mb-5 leading-normal'>You can practice any <span className='text-secondary'>time convinent for you.</span></h2>
                    <p className='text-tartiary text-lg mb-7'>A good example of a paragraph contains a topic conclusion. There are many different 
                        kinds of animals that live in China.</p>
                    <button className='btnPrimary'>Get Started</button>
                </motion.div>

            </div>
        </div>
    );
};

export default About;
