// src/app/components/newsletter/newsletter.component.ts
import { Component } from '@angular/core';
import { BannerComponent } from '../../shared/banner/banner.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-newsletter',
  standalone: true,
  imports: [BannerComponent, CommonModule],
  templateUrl: './newsletter.component.html',
  styleUrl: './newsletter.component.css'
})
export class NewsletterComponent {

}

<div class="md:px-14 p-4 max-w-screen-2xl mx-auto my-12">
  <app-banner heading="Each student an share their discount code for friends"
  subheading="A simple paragraph is comprised of three major components. the first sentence, which is ofthen a declarative sentence, is called the topic sentence."
  btn1="I have a code" btn2=""/>
</div>

// src/components/Newsletter.jsx
import Banner from "../shared/Banner";

const Newsletter = () => {
    return (
        <div className="md:px-14 p-4 max-w-screen-2xl mx-auto my-12">
            <Banner heading={"Each student an share their discount code for friends"} subheading={"A simple paragraph is comprised of three major components. the first sentence, which is ofthen a declarative sentence, is called the topic sentence."} btn1={"I have a code"} btn2={""}/>
        </div>
    );
};

export default Newsletter;
