// src/shared/Footer.jsx
import react from '../assets/react.png'
import facebook from '../assets/facebook.png'
import instagram from '../assets/Instagram.png'
import twitter from '../assets/Twitter.png'
import linkedin from '../assets/Linkedin.png'

const Footer = () => {
    return (
        <div className="bg-[#010851] md:px-14 p-4 max-w-screen-2xl mx-auto text-white">
            <div className='my-12 flex flex-col md:flex-row gap-10'>
                <div className='md:w-1/2 space-y-8'>
                    <a href="/" className="text-2xl font-semibold flex items-center space-x-3 text-primary">
                        <img src={react} className="w-10 inline-block items-center" /> <span className='text-white'>XYZ</span>
                    </a>
                    <p className='md:w-1/2 '>A simple paragraph is comprised of three major components.
                        The first sentence, which if often a declarative sentence.</p>
                    <div>
                        <input type="email" name="email" id="email" placeholder='email'
                            className='bg-[#9a7af159] py-2 px-4 rounded-md focus:outline-none' />
                        <input type="submit" value='Subscribe' className='px-4 py-2 bg-secondary rounded-md -ml-2 
                        cursor-pointer hover:bg-white hover:text-primary duration-300 transition-all'/>
                    </div>

                </div>
                <div className='md:w-1/2 flex flex-col md:flex-row flex-wrap justify-between gap-8 items-start'>
                    <div className='space-y-4 mt-5'>
                        <h4 className='text-xl'>Platform</h4>
                        <ul className='space-y-3'>
                            <a href="/" className='block hover:text-gray-300'>Overview</a>
                            <a href="/" className='block hover:text-gray-300'>Features</a>
                            <a href="/" className='block hover:text-gray-300'>About</a>
                            <a href="/" className='block hover:text-gray-300'>Pricing</a>

                        </ul>
                    </div>
                    
                    <div className='space-y-4 mt-5'>
                        <h4 className='text-xl'>Platform</h4>
                        <ul className='space-y-3'>
                            <a href="/" className='block hover:text-gray-300'>Overview</a>
                            <a href="/" className='block hover:text-gray-300'>Features</a>
                            <a href="/" className='block hover:text-gray-300'>About</a>
                            <a href="/" className='block hover:text-gray-300'>Pricing</a>

                        </ul>
                    </div>

                    <div className='space-y-4 mt-5'>
                        <h4 className='text-xl'>Contacts</h4>
                        <ul className='space-y-3'>
                            <a href="/" className='block hover:text-gray-300'>(021) 132-231</a>
                            <a href="/" className='block hover:text-gray-300'>321 XYZ XYZ</a>
                            <a href="/" className='block hover:text-gray-300'>Asuncion-Paraguay</a>
                            <a href="/" className='block hover:text-gray-300'>1506</a>
                        </ul>
                    </div>
                </div>
            </div>
            <hr />
            <div className='flex flex-col sm:flex-row gap-8 sm:items-center justify-between my-8'>
                <p>@ XYZ 20XX --- 20XX. All rights reserved.</p>
                <div className='flex items-center space-x-5'>
                    <img src={facebook} alt="" className='w-8 cursor-pointer hover:-translate-y-4  transition-all duration-300'/>
                    <img src={instagram} alt="" className='w-8 cursor-pointer hover:-translate-y-4  transition-all duration-300'/>
                    <img src={twitter} alt="" className='w-8 cursor-pointer hover:-translate-y-4  transition-all duration-300'/>
                    <img src={linkedin} alt="" className='w-8 cursor-pointer hover:-translate-y-4  transition-all duration-300'/>

                </div>
            </div>
        </div>
    );
};

export default Footer;

// src/app/shared/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {
  react = '../../../assets/react.png'
  facebook = '../../../assets/facebook.png'
  instagram = '../../../assets/Instagram.png'
  linkedin = '../../../assets/Linkedin.png'
  twitter = '../../../assets/Twitter.png'
}

<div Class="bg-[#010851] md:px-14 p-4 max-w-screen-2xl mx-auto text-white">
  <div Class='my-12 flex flex-col md:flex-row gap-10'>
      <div Class='md:w-1/2 space-y-8'>
          <a href="/" Class="text-2xl font-semibold flex items-center space-x-3 text-primary">
              <img src={{react}} Class="w-10 inline-block items-center" /> <span Class='text-white'>XYZ</span>
          </a>
          <p Class='md:w-1/2 '>A simple paragraph is comprised of three major components.
              The first sentence, which if often a declarative sentence.</p>
          <div>
              <input type="email" name="email" id="email" placeholder='email'
                  Class='bg-[#9a7af159] py-2 px-4 rounded-md focus:outline-none' />
              <input type="submit" value='Subscribe' Class='px-4 py-2 bg-secondary rounded-md -ml-2
              cursor-pointer hover:bg-white hover:text-primary duration-300 transition-all'/>
          </div>

      </div>
      <div Class='md:w-1/2 flex flex-col md:flex-row flex-wrap justify-between gap-8 items-start'>
          <div Class='space-y-4 mt-5'>
              <h4 Class='text-xl'>Platform</h4>
              <ul Class='space-y-3'>
                  <a href="/" Class='block hover:text-gray-300'>Overview</a>
                  <a href="/" Class='block hover:text-gray-300'>Features</a>
                  <a href="/" Class='block hover:text-gray-300'>About</a>
                  <a href="/" Class='block hover:text-gray-300'>Pricing</a>

              </ul>
          </div>

          <div Class='space-y-4 mt-5'>
              <h4 Class='text-xl'>Platform</h4>
              <ul Class='space-y-3'>
                  <a href="/" Class='block hover:text-gray-300'>Overview</a>
                  <a href="/" Class='block hover:text-gray-300'>Features</a>
                  <a href="/" Class='block hover:text-gray-300'>About</a>
                  <a href="/" Class='block hover:text-gray-300'>Pricing</a>

              </ul>
          </div>

          <div Class='space-y-4 mt-5'>
              <h4 Class='text-xl'>Contacts</h4>
              <ul Class='space-y-3'>
                  <a href="/" Class='block hover:text-gray-300'>(021) 132-231</a>
                  <a href="/" Class='block hover:text-gray-300'>321 XYZ XYZ</a>
                  <a href="/" Class='block hover:text-gray-300'>Asuncion-Paraguay</a>
                  <a href="/" Class='block hover:text-gray-300'>1506</a>
              </ul>
          </div>
      </div>
  </div>
  <hr />
  <div Class='flex flex-col sm:flex-row gap-8 sm:items-center justify-between my-8'>
      <p> XYZ 20XX --- 20XX. All rights reserved.</p>
      <div Class='flex items-center space-x-5'>
          <img src={{facebook}} alt="" Class='w-8 cursor-pointer hover:-translate-y-4  transition-all duration-300'/>
          <img src={{instagram}} alt="" Class='w-8 cursor-pointer hover:-translate-y-4  transition-all duration-300'/>
          <img src={{twitter}} alt="" Class='w-8 cursor-pointer hover:-translate-y-4  transition-all duration-300'/>
          <img src={{linkedin}} alt="" Class='w-8 cursor-pointer hover:-translate-y-4  transition-all duration-300'/>

      </div>
  </div>
</div>
